/*
 * SafetyPayDirectMiddleLayerV20.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/21/2016
 */
using System;
using SafetyPayDirectMiddleLayerV20.PCL.Controllers;

namespace SafetyPayDirectMiddleLayerV20.PCL
{
    public partial class SafetyPayDirectMiddleLayerV20Client
    {

        /// <summary>
        /// Singleton access to CustomerSection controller
        /// </summary>
        public CustomerSectionController CustomerSection
        {
            get
            {
                return CustomerSectionController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to UserSection controller
        /// </summary>
        public UserSectionController UserSection
        {
            get
            {
                return UserSectionController.Instance;
            }
        }

        /// <summary>
        /// Client constructor
        /// </summary>
        public SafetyPayDirectMiddleLayerV20Client()
        {
        }
    }
}